### ISSUE TITLE
need swipe gesture

### ISSUE THREAD

**Issue by kangmifhd** [quartack/bdapter#2]
how to handle swipe gesture in bdapter recyclerVew?

**Comment by quartack** [comment]
The question is a little insufficient, but there is nothing special about bdapter to handle it differently.
If you want to manage view touch in a specific viewholder, checkout [this](https://github.com/quartack/bdapter_sample/blob/main/app/src/main/java/com/quartack/bdapter/sample/event/model/EventItem.kt#L20). You can access the view via  holder.binding.xxx.

**Comment by quartack** [comment]
> how to handle swipe gesture in bdapter recyclerVew?

The question is a little insufficient, but there is nothing special about bdapter to handle it differently.
If you want to manage view touch in a specific viewholder, checkout [this](https://github.com/quartack/bdapter_sample/blob/main/app/src/main/java/com/quartack/bdapter/sample/event/model/EventItem.kt#L20). You can access the view via holder.binding.xxx.
